# Generated by Django 5.2 on 2025-05-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0004_userpath'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpath',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userpath',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
